keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
lists:
  - filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
    hidden: true
    id: 0
    name: What's Due?
  - hidden: true
    ignore: false
    name: NOTE
  - hidden: false
    name: TODO
  - hidden: false
    name: DOING
  - hidden: false
    ignore: true
    name: DONE
  - filter: 'completedDate > "${14 days ago}" -completed'
    hidden: false
    id: 1
    name: Recently Completed
  - name: FIXME
    hidden: true
    ignore: false
  - name: HACK
    hidden: true
    ignore: false
  - name: XXX
    hidden: true
    ignore: false
  - name: IDEA
    hidden: false
    ignore: false
settings:
  openIn: default
  customOpenIn: ''
  editorTheme: blackboard
  journalType: Single File
  journalPath: null
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: MARKDOWN
  replaceSpacesWith: '-'
  plugins:
    devMode: false
  filteredLists:
    - filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
      name: What's Due?
    - filter: 'completedDate > "${7 days ago}" -completed'
      name: Recently Completed
  journalTemplate: null
  theme: dark
  addCheckBoxTasks: false
  name: template_fastapi
  views:
    - id: default
      filter: ''
  cards:
    colors: []
    template: |

      <!--
      created:${timestamp}
      -->
    trackChanges: false
    metaNewLine: false
    addCompletedMeta: true
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: '#'
    tagPrefix: '#'
    metaSep: ':'
    maxLines: 6
    addNewCardsToTop: true
    defaultList: TODO
    computed: !<tag:yaml.org,2002:js/undefined> ''
